# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-15 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_mainshow'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mainshow',
            table='miya_mainshow',
        ),
    ]
