# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-15 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190315_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productimg', models.CharField(max_length=200)),
                ('productname', models.CharField(max_length=100)),
                ('productlongname', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('marketprice', models.FloatField()),
                ('productnum', models.IntegerField()),
            ],
            options={
                'db_table': 'miya_goods',
            },
        ),
    ]
